/**
 * Image/video QA scoring rubric (impl plan §6.5, M4) — ported verbatim from
 * the AWS-side `dialogue-basic-qa-agent`'s `image_evaluator.py`/
 * `video_evaluator.py`/`config.py`: same system prompts, same weight
 * tables, same threshold constants, same weighted-sum-then-three-way-
 * bucket logic. Pure functions only — no LLM call, no DB, no clock (same
 * contract as `steps/builders/*.ts`). The VLM call itself is
 * `quality/replicate.ts`'s `callVisionJson`.
 *
 * Dialogue-Basic's rubric fits QM's narration-basic/premium tiers directly:
 * both are "image driven purely by imagePrompt, no narration-text
 * alignment to check" scenes (QM's narration ends up as a TTS track, not a
 * visual constraint on the image) — ported without adaptation.
 */

export type ImageIssueCategory =
  | 'PROMPT_VISUAL_MISMATCH'
  | 'IDENTITY_MISMATCH'
  | 'HALLUCINATION_VISUAL'
  | 'WARDROBE_VIOLATION'
  | 'ANATOMY_DEFECT'
  | 'ENVIRONMENT_MISMATCH'
  | 'BLOCKING_ERROR'
  | 'PROMPT_QUALITY';

export type VideoIssueCategory =
  | 'MOTION_QUALITY'
  | 'TEMPORAL_DRIFT'
  | 'PROMPT_VISUAL_MISMATCH'
  | 'HALLUCINATION_VISUAL'
  | 'CONTINUITY_BREAK'
  | 'ANATOMY_DEFECT';

export type IssuePriority = 'P0' | 'P1' | 'P2' | 'P3';

export interface Issue {
  category: string;
  priority: IssuePriority;
  description: string;
  evidence?: Record<string, unknown>;
}

export type PassStatus = 'PASS' | 'REWORK' | 'FAIL' | 'GATED';

export interface GateResult {
  weightedScore: number | null;
  scores: Record<string, number>;
  issues: Issue[];
  summary: string;
  passStatus: PassStatus;
}

export interface VideoGateResult extends GateResult {
  motionTypeDetected: string | null;
  gatedOut: boolean;
}

export const IMAGE_QA_WEIGHTS: Record<string, number> = {
  prompt_alignment: 0.2,
  character_identity: 0.15,
  environment_setting: 0.15,
  composition_framing: 0.1,
  hallucination_control: 0.3,
  anatomy_correctness: 0.1,
};

export const VIDEO_QA_WEIGHTS: Record<string, number> = {
  motion_prompt_alignment: 0.25,
  motion_quality: 0.2,
  character_continuity: 0.2,
  camera_motion_quality: 0.1,
  hallucination_temporal: 0.25,
};

export const IMAGE_QA_SYSTEM_PROMPT = `You are a professional visual QA analyst for AI-generated video scene images.

You will receive:
1. The image prompt used to generate the image
2. The motion prompt describing the motion this image will be animated into (context only)
3. Whether a character reference image was used (identity should be preserved if so)
4. The image URL to evaluate

CRITICAL CHECKS:
- PROMPT ALIGNMENT: Does the image visually represent the core subject/action described
  in the image prompt? Extract key nouns/actions from the prompt — they must be visible.
- HALLUCINATION (the single most important check): Count every instance of the main
  subject/character. There must be EXACTLY the number of people/characters the prompt
  describes — flag ANY duplicate, mirrored, or extra copy of the same character (e.g. two
  heads on one body, the same person appearing multiple times fanned out in one frame).
  This is a P0 blocking defect, never a minor note.
- ANATOMY: Correct number of heads, arms, legs, fingers per person. Flag fused limbs,
  extra limbs, or any anatomically impossible configuration as ANATOMY_DEFECT.
- CHARACTER IDENTITY: If a reference image was used, does the generated character's
  appearance (face, build, clothing) match it?
- ENVIRONMENT: Does location, lighting, and atmosphere match the prompt's setting?
- COMPOSITION: Is the framing/camera angle sensible and matches any framing cues in the prompt?

Score each dimension from 0.0 to 10.0. Be strict — only give 9+ for near-perfect results.
Any duplicate-body or extra-limb hallucination should drive hallucination_control and/or
anatomy_correctness to 2.0 or below, regardless of how good the rest of the image looks.

Return ONLY a JSON object with this exact structure:
{
  "scores": {
    "prompt_alignment": <float 0-10>,
    "character_identity": <float 0-10>,
    "environment_setting": <float 0-10>,
    "composition_framing": <float 0-10>,
    "hallucination_control": <float 0-10>,
    "anatomy_correctness": <float 0-10>
  },
  "issues": [
    {
      "category": "<PROMPT_VISUAL_MISMATCH|IDENTITY_MISMATCH|HALLUCINATION_VISUAL|WARDROBE_VIOLATION|ANATOMY_DEFECT|ENVIRONMENT_MISMATCH|BLOCKING_ERROR|PROMPT_QUALITY>",
      "priority": "<P0|P1|P2|P3>",
      "description": "<concise issue description>",
      "evidence": { "expected": "<what should be there>", "observed": "<what is actually there>" }
    }
  ],
  "summary": "<1-2 sentence overall assessment>"
}`;

export const VIDEO_QA_SYSTEM_PROMPT = `You are a professional video QA analyst for AI-generated silent scene clips.

Context: these clips are generated by an image-to-video model from a single source still
image, driven by a motion prompt. Each clip is roughly 3-7 seconds long.

You will receive:
1. The video (motion) prompt used to generate the clip
2. The video URL to evaluate

CRITICAL CHECKS:
1. MOTION QUALITY: The clip should not be a frozen slideshow, but should also not have
   erratic/warping motion. A completely static clip = MOTION_QUALITY P1.
2. MOTION-PROMPT ALIGNMENT: Does the motion in the clip match what the video prompt
   describes?
3. HALLUCINATION / DUPLICATE BODIES (the single most important check): If the clip shows
   more instances of the main character/subject than intended — e.g. a duplicated body,
   two heads on one figure, or the same person appearing multiple times — this is a P0
   HALLUCINATION_VISUAL defect. The animator typically inherits and can even amplify this
   defect as the clip moves (e.g. duplicate limbs separating during motion). Watch the
   full clip, not just the first frame.
4. CHARACTER CONTINUITY: Character appearance and body-count must be stable throughout —
   flag if the number of visible bodies/limbs changes mid-clip.
5. CAMERA: Camera motion should be smooth and intentional. Jittery drift = MOTION_QUALITY P1.
6. NO NEW CHARACTERS: No figures should drift into frame that weren't in the source image.

Score each dimension from 0.0 to 10.0. Be strict. Any duplicate-body hallucination should
drive hallucination_temporal to 2.0 or below regardless of how smooth the motion looks.

Return ONLY a JSON object:
{
  "scores": {
    "motion_prompt_alignment": <float 0-10>,
    "motion_quality": <float 0-10>,
    "character_continuity": <float 0-10>,
    "camera_motion_quality": <float 0-10>,
    "hallucination_temporal": <float 0-10>
  },
  "motion_type_detected": "<ambient|character|frozen|mixed>",
  "issues": [
    {
      "category": "<MOTION_QUALITY|TEMPORAL_DRIFT|PROMPT_VISUAL_MISMATCH|HALLUCINATION_VISUAL|CONTINUITY_BREAK|ANATOMY_DEFECT>",
      "priority": "<P0|P1|P2|P3>",
      "description": "<concise issue description>",
      "evidence": { "expected": "<what should happen>", "observed": "<what actually happens>", "timestamp_estimate": "<e.g. 0-2s, 3-5s, throughout>" }
    }
  ],
  "summary": "<1-2 sentence overall video assessment>"
}`;

function weightedSum(scores: Record<string, number>, weights: Record<string, number>): number {
  let sum = 0;
  for (const [dim, weight] of Object.entries(weights)) {
    sum += (scores[dim] ?? 0) * weight;
  }
  return Math.round(sum * 100) / 100;
}

export interface ImageGateThresholds {
  passThreshold: number;
  reviewThreshold: number;
}

/** Buckets a raw VLM JSON response into the {weightedScore, scores, issues,
 * summary, passStatus} shape. Does not call the VLM — pure function over an
 * already-parsed response, matching image_evaluator.py's post-call logic. */
export function scoreImage(vlmResult: { scores?: Record<string, number>; issues?: Issue[]; summary?: string }, thresholds: ImageGateThresholds): GateResult {
  const scores = vlmResult.scores ?? {};
  const weightedScore = weightedSum(scores, IMAGE_QA_WEIGHTS);
  const passStatus: PassStatus =
    weightedScore >= thresholds.passThreshold ? 'PASS' : weightedScore >= thresholds.reviewThreshold ? 'REWORK' : 'FAIL';
  return { weightedScore, scores, issues: vlmResult.issues ?? [], summary: vlmResult.summary ?? '', passStatus };
}

export function imageEvalFailedResult(reason: string): GateResult {
  return {
    weightedScore: 0,
    scores: {},
    issues: [{ category: 'PROMPT_QUALITY', priority: 'P0', description: reason, evidence: {} }],
    summary: 'Evaluation failed',
    passStatus: 'FAIL',
  };
}

export interface VideoGateThresholds {
  gateThreshold: number;
  passThreshold: number;
  reviewThreshold: number;
}

/** Mirrors video_evaluator.py's gate-by-image-score pre-check — skip the
 * (costly) video VLM call entirely when the source image already scored
 * too low to plausibly pass, since the animator inherits the source
 * frame's defects rather than fixing them. */
export function isVideoGatedByImageScore(imageQaScore: number, thresholds: VideoGateThresholds): boolean {
  return imageQaScore < thresholds.gateThreshold;
}

export function videoGatedResult(imageQaScore: number, thresholds: VideoGateThresholds): VideoGateResult {
  return {
    weightedScore: null,
    scores: {},
    issues: [],
    motionTypeDetected: null,
    summary: `Video QA skipped — image score ${imageQaScore.toFixed(2)} < gate threshold ${thresholds.gateThreshold}`,
    passStatus: 'GATED',
    gatedOut: true,
  };
}

export function scoreVideo(
  vlmResult: { scores?: Record<string, number>; motion_type_detected?: string; issues?: Issue[]; summary?: string },
  thresholds: VideoGateThresholds,
): VideoGateResult {
  const scores = vlmResult.scores ?? {};
  const weightedScore = weightedSum(scores, VIDEO_QA_WEIGHTS);
  const passStatus: PassStatus =
    weightedScore >= thresholds.passThreshold ? 'PASS' : weightedScore >= thresholds.reviewThreshold ? 'REWORK' : 'FAIL';
  return {
    weightedScore,
    scores,
    issues: vlmResult.issues ?? [],
    motionTypeDetected: vlmResult.motion_type_detected ?? null,
    summary: vlmResult.summary ?? '',
    passStatus,
    gatedOut: false,
  };
}

export function videoEvalFailedResult(reason: string): VideoGateResult {
  return {
    weightedScore: 0,
    scores: {},
    issues: [{ category: 'MOTION_QUALITY', priority: 'P0', description: reason, evidence: {} }],
    motionTypeDetected: null,
    summary: 'Evaluation failed',
    passStatus: 'FAIL',
    gatedOut: false,
  };
}
